# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='subject',
        ),
        migrations.AddField(
            model_name='poll',
            name='subject',
            field=models.ManyToManyField(to='polls.Subject'),
        ),
    ]
