# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170817_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='subject',
        ),
        migrations.AddField(
            model_name='poll',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Subject'),
            preserve_default=False,
        ),
    ]
