# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170818_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='poll',
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Subject'),
            preserve_default=False,
        ),
    ]
